"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-+h@!!!&p1=fp8hlqrdrh$rae%!flza%03(!-gy3d8hi8ido-p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition
SITE_ID = 1
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',
    'taggit',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.weibo',
    'allauth.socialaccount.providers.weixin',
    'allauth.socialaccount.providers.baidu',
    'myaccount',
    'widget_tweaks',
    'notice',
    'crispy_forms', # bootstrap表单样式
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(BASE_DIR,)],
        'DIRS': [os.path.join(BASE_DIR,)] + [os.path.join(BASE_DIR, 'myaccount/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False



# 基本设定
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # 登录模式可选 用户名和邮箱
ACCOUNT_EMAIL_REQUIRED = True
LOGIN_REDIRECT_URL = '/' # 登录成功后重新定向的页面

ACCOUNT_SIGNUP_FORM_CLASS = 'myaccount.forms.SignupForm'


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 邮箱设定
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'liu1xufeng@gmail.com'
# EMAIL_HOST_PASSWORD = 'lxf79881237'
# EMAIL_PORT = '25'
# EMAIL_USE_TLS = True
# EMAIL_FROM = 'liu1xufeng@gmail.com'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# qq邮箱设定
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '286447897@qq.com' # 你的 QQ 账号和授权码
EMAIL_HOST_PASSWORD = 'qcxkpcnfxcuqbidg'
EMAIL_USE_TLS = True  # 这里必须是 True，否则发送不成功
EMAIL_FROM = '286447897@qq.com' # 你的 QQ 账号
DEFAULT_FROM_EMAIL = '286447897@qq.com'


# # 新浪邮箱设定
# EMAIL_HOST = 'smtp.sina.com'
# EMAIL_PORT = 25
# EMAIL_HOST_USER = 'liuxufeng456@sina.com' # 你的 QQ 账号和授权码
# EMAIL_HOST_PASSWORD = 'lxf79881237'
# EMAIL_USE_TLS = True  # 这里必须是 True，否则发送不成功
# EMAIL_FROM = '286447897@qq.com' # 你的 QQ 账号
# DEFAULT_FROM_EMAIL = '286447897@qq.com'

# API Key：
# FVhNDcq4TRM56BIcIHEXjUnb
# Secret Key：
# D25AiP25389iFEIge13zcRgCYTPp7dzp


MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')     #设置静态文件路径为主目录下的media文件夹
MEDIA_URL = '/media/'
