# Generated by Django 2.2.7 on 2019-12-24 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 14, 21, 6, 202210, tzinfo=utc), verbose_name='发表时间'),
        ),
    ]
