# Generated by Django 2.2.7 on 2019-12-29 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191228_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 29, 3, 3, 43, 158280, tzinfo=utc), verbose_name='发表时间'),
        ),
    ]
