# Generated by Django 2.2.4 on 2020-01-04 02:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200104_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 2, 1, 8, 411493, tzinfo=utc), verbose_name='发表时间'),
        ),
    ]
