# Generated by Django 2.2.7 on 2020-01-05 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200104_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_recommend',
            field=models.BooleanField(default=0, verbose_name='是否今日推荐'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 7, 58, 38, 216265, tzinfo=utc), verbose_name='发表时间'),
        ),
    ]
