# Generated by Django 2.2.4 on 2020-01-07 03:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200107_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 3, 58, 4, 869761, tzinfo=utc), verbose_name='发表时间'),
        ),
    ]
