# Generated by Django 2.2.7 on 2020-01-12 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200107_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 6, 26, 14, 129119, tzinfo=utc), verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish', verbose_name='唯一标识'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', '发布'), ('draft', '不发布')], default='published', max_length=10, verbose_name='是否显示'),
        ),
    ]
