# Generated by Django 2.2.7 on 2020-02-19 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='公告标题')),
                ('body', models.TextField(verbose_name='公告内容')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
    ]
