# Generated by Django 2.2.7 on 2020-01-05 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 7, 58, 38, 247183, tzinfo=utc), verbose_name='发表时间'),
        ),
    ]
