# Generated by Django 2.2.4 on 2020-01-06 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20200105_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 5, 32, 31, 723271, tzinfo=utc), verbose_name='发表时间'),
        ),
    ]
