# Generated by Django 2.2.4 on 2020-01-07 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20200106_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 3, 48, 21, 753000, tzinfo=utc), verbose_name='发表时间'),
        ),
    ]
