# Generated by Django 2.2.7 on 2020-01-12 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20200107_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 6, 26, 14, 161328, tzinfo=utc), verbose_name='发表时间'),
        ),
    ]
