# Generated by Django 2.2.7 on 2020-02-17 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_auto_20200112_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间'),
        ),
    ]
