# Generated by Django 2.2.7 on 2020-02-19 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, upload_to='user_img')),
                ('org', models.CharField(blank=True, max_length=128, verbose_name='组织')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='手机号码')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '个人资料',
            },
        ),
    ]
