# Generated by Django 2.2.7 on 2020-01-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='user_img'),
        ),
    ]
